id = "RAYTRAC3RCosmetics"
name = "RAYTRAC3RCosmetics"
description = "Lure-based mod that adds a bunch of cosmetics and 3 new species including llamas and penguins!"
version = "0.5.3"
homepage = "https://github.com/RAYTRAC3R/RAYTRAC3R-s-Cosmetics/"
author = "RAYTRAC3R"

icon = "icon.png"
readme = "README.md"
changelog = "CHANGELOG.md" # optional

# both are optional here, pick what you want
[project]
godot = "C:/samidev/RAYTRAC3R-s-Cosmetics/project.godot"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.13"

# example dependency
[[dependencies]]
id = "Sulayre.Lure"
thunderstore_version = "Sulayre-Lure-4.2.1"